### ISSUE TITLE
Is there anyway to support association/ relationships?

### ISSUE THREAD

**Issue by sonhnguyen** [bombsimon/gorm-bulk#7]
I am currently using many `has_many` relationships and gorm default creating relationships on `db.create` has been important. Is there a way to do it?

**Comment by bombsimon** [comment]
You could create your own insert function, [see examples](https://github.com/bombsimon/gorm-bulk/blob/master/examples/bulk_insert.go#L49-L68). However I'm not sure if that would allow you to perform this in an easy way.

I'll try to find time to look into the possibility to do this automatically. Since bulk inserting doesn't return the created records there's no easy way to do a new insert for related fields with known IDs, however it would probably not be too hard to do an insert with a `JOIN` statement.

**Comment by bombsimon** [comment]
I didn't really think this through, you cannot insert to more than one table at once. The only way I can think of to support this is to use `LASERT_INSERT_ID()` and we don't get that from the bulk insert.

Feel free to add your thoughts on how this would be implemented.

One way would be to do the insert in bulk and then define some kind of constraint that would let me get a specific row without ID, i.e. an email address, a username etcetera. Then with that information one could retrieve the ID for all the records an map them to the struct based on the constraints. When that's done we know the ID for all the structs and can insert (in bulk or not) in the relational table.

But it seems like a not so nice path to go and I'm not sure if it should be a part of this library. I'll see if I can find some time to do some testing this weekend but don't get your hopes up for any final solution.

**Comment by bombsimon** [comment]
Closing this since I can't find a good way to handle this and the issue has been stale since over a month. Also, Gorm v2 is coming out soon which will have support for bulk insert natively so this project will probably be archived.
